title: Mon Site Jekyll
email: your-email@example.com
description: >- # cette ligne permet les line breaks dans la description
  Un projet Jekyll minimal avec Bulma.
baseurl: "" # pour les déploiements locaux
url: "" # URL de production

sass:
  sass_dir: assets/css
  style: compressed

markdown: kramdown
plugins:
  - jekyll-feed




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
